eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          binder: kafka
          destination: test
          content-type: application/json
          group: input-group-1
        output:
          binder: kafka
          destination: test
          group: output-group-1
          content-type: application/json
